services:
  chatrabash.server:
    image: ${DOCKER_REGISTRY-}chatrabashserver
    build:
      context: .
      dockerfile: chatrabash.server/API/Dockerfile

  chatrabash.client:
    image: ${DOCKER_REGISTRY-}chatrabashclient
    build:
      context: ./chatrabash.client
      dockerfile: Dockerfile